### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by conconnl**
New CSP requirement for hcaptcha

### CODE REVIEW

**Comment by conconnl** [comment]
Why do you close this without saying anything?

**Comment by sebastienlapoux** [comment]
mention of CSP hcaptcha were already on the htacess file

**Comment by conconnl** [comment]
This is a wrong assessment.
As you can see the current htaccess has 6 times hcaptcha an the new one 8 times.

The reason you have Github is to check a merge the changes and then put the file on the server.
Doing the manual changes in the file on the server, will just make sure things will be lost in the end.
GitHub is the versioning system and the file in GitHub is the one which will just override the one on the server, if it doesn't reflect a change, that change will disappear with an override.

**Comment by sebastienlapoux** [comment]
Ok, thanks for the clarification Wilco.

**Comment by PriyanshSarvehi** [comment]
> New CSP requirement for hcaptcha

Is there any such project or issue I can help you with??

**Comment by sebastienlapoux** [comment]
thanks @conconnl !

**Pull request merged**
